###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3'
services:
    redis:
        container_name: redis
        image: 'redis:alpine'
        ports:
            - '6379:6379'

    webserver:
        container_name: nginx
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './php:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        container_name: php
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - './php:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    angular:
        container_name: angular
        build: frontend
        working_dir: /app
        environment:
            SHELL: /bin/bash
            NODE_ENV: development
        volumes:
            - './frontend/src:/app/src'
        ports:
            - '4200:4200'
        command: >
            bash -c "npm install && npm start"
